remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Gurobi Modeling Examples]
description: [Explore our modeling examples for the Python API]
show_downloads: [true] # to indicate whether to provide a download URL